### ISSUE TITLE
add opt-out for specific coins

### ISSUE THREAD

**Issue by elkimek** [wrkzcoin/TipBot#1]
Hey, can we please have an opt-out for getting tipped certain coins? Or disable all by default and let people enable only those they are interested in?

There is a lot of tipping spam ongoing on TurtleCoin server just because the coins have no value. 

Thank you! :)

**Comment by wrkzdev** [comment]
We can consider how to make this better with your suggestion.

**Comment by wrkzdev** [comment]
Should be closed now. TRTL discord server tipping only TRTL.

Moreover, we have a command of allowable coins:
`.setting tiponly coin1 coin2 .. `
