### ISSUE TITLE
[FEATURES REQUEST] info on token supported

### ISSUE THREAD

**Issue by banine** [wrkzcoin/TipBot#16]
an example is DEGO,..
if use `.cg dego` will return result Dego Finance Rank #684 which is wrong information (the right token but not supported on tipbot).
Would help with info on the tokens/coins available on the tipbot.

something like `.info <TICKER>`

then return
`<coin name> - <ticker>`
`<supported chain1><supported chain2><supported chain3>`
`<token type1> <token type2> <token type3> `
`<contract address1><contract address2><contract address3>`
`<url to check price / graph>`
`<other related info>`

**Comment by wrkzdev** [comment]
Thank you.

**Comment by wrkzdev** [comment]
This was implemented and updated.
