### ISSUE TITLE
Timeout issue with wallet rpc

### ISSUE THREAD

**Issue by wrkzdev** [wrkzcoin/TipBot#2]
There is a known issue about timeout with wallet rpc which took longer than our default setting 32 seconds and bot assumes that the tx sending or tipping is failed. Then bot tells the tipper or sender that it is failed while wallet service awaits the execution longer and succeed after. Bot should have told to the tipper/sender and the receiver(s) after succeed but not, because of the timeout.

We increased the timeout for method `sendTransaction` in https://github.com/wrkzcoin/TipBot/blob/multi-tipbot/wrkzcoin_tipbot/rpc_client.py#L31 to 180s.

**Comment by bobbieltd** [comment]
Not sure if related. Try to set this too : https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout

**Comment by wrkzdev** [comment]
This could happen that when an rpc requests to the wallet-service of a coin, and wallet-service doesn't request to daemon OR give a respond back yet because it was occupied by other load(s). Then the request is (probably) on queue and executed to daemon OR returned the respond back very late.

Increasing it to 180s waiting time or longer is still not solved the issue yet. As far as I know, the default timeout of aiohttp is 300s.

**Comment by wrkzdev** [comment]
This shall be resolved now.
* Increase timeout
* Allow only one Tx at a time for a single user.
